name: Sync README.md

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v4

      - name: Fetch README.md from source repo
        run: |
          curl -o README.md https://raw.githubusercontent.com/kostable/kumeka_bootcamp/main/README.md
          git config --global user.name "yaros18"
          git config --global user.email "qazw63@gmail.com"
          git add README.md
          git commit -m "Update README.md from source repo" || echo "No changes to commit"
          git push
